### ISSUE TITLE
add installation instructions/command

### ISSUE THREAD

**Issue by kuhe** [SNUDerek/multiLSTM#2]
I aint understandin no corpses en no notebooks.

- python version

- python dependency installation command (use a standard dependency manager)

- data file dependency installation command (download or version it in here)

- commands to run the rest of installation "network training"

- and lastly a command to verify it all worked

**Comment by kuhe** [comment]
@SNUDerek

**Comment by yzho0907** [comment]
I tested the env under python3.5+tf1.9.0+keras2.2.0
after u install the conda with python3, u could try:
pip3 install pandas
pip3 install gensim
pip3 install tensorflow
pip3 install keras
pip3 install git+https://www.github.com/keras-team/keras-contrib.git
pip3 install keras-utilities
then, u should be able to run the code
